### ISSUE TITLE
When a field is null, its value is transformed to 0.0 for a double and 0 for a long instead of the empty string

### ISSUE THREAD

**Issue by iDmple** [YannBrrd/elasticsearch-entity-resolution#16]
When a field is null, its value is transformed to 0.0 for a double and 0 for a long instead of the empty string. Because of that if I compare a non-null double to null double, it doesn't skip the comparison and I get the LOW probability selected and the record gets a very low score. Same goes for long.

Example:
"185.5" to null compares "185.5" to "0.0"...

Here is the problematic code for double:

        if (field instanceof ScriptDocValues.Doubles) {
                result = Double.toString(((ScriptDocValues.Doubles) field).getValue());
        }

I replaced it by:
        if (field instanceof ScriptDocValues.Doubles) {
            if(!((ScriptDocValues.Doubles) field).isEmpty()) {
                result = Double.toString(((ScriptDocValues.Doubles) field).getValue());
            } else {
                result = "";
            }
        }

If I do the same for long, your tests fail and I don't understand why. So this is probably not the right way to fix, but I'm not sure how else I can.

Can you please advise ASAP?

Best regards

**Comment by iDmple** [comment]
I think this seems to cause the issue:

193        public double getValue() {
194            int numValues = values.setDocument(docId);
195            if (numValues == 0) {
196                return 0d;
197            }
198            return values.nextValue();
199        }

if there is no value it returns 0d.

**Comment by iDmple** [comment]
So I managed to make it compile. It seems the tests are failing in a non deterministic manner?

Unsure what is going on there.

**Comment by YannBrrd** [comment]
Having à strange behaviour with a test. Scoring is not deterministic which
is strange (see #3)

Le mar. 6 oct. 2015 11:31, iDmple <notifications@github.com> a écrit :

> So I managed to make it compile. It seems the tests are failing in a non
> deterministic manner?
>
> Unsure what is going on there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YannBrrd/elasticsearch-entity-resolution/issues/16#issuecomment-145797581>
> .
>
-- 
Cordialement,
Yann Barraud

**Comment by iDmple** [comment]
I see. I fixed the bug I mentioned but it looks more like a hack. Unsure how to do it better.
