### ISSUE TITLE
Does this scale to large data

### ISSUE THREAD

**Issue by lminer** [YannBrrd/elasticsearch-entity-resolution#17]
I have a 150 gig mysql table that I'm trying to dedupe. If I throw the data in elastic search, will this implementation work on this much data? Will I need to purchase some monster instance on amazon?

**Comment by YannBrrd** [comment]
Hi,

You should try to use Duke instead. https://github.com/larsga/Duke/wiki/GettingStarted 

Cheers,
Yann
