### ISSUE TITLE
Support for elasticsearch 2.1.0

### ISSUE THREAD

**Issue by cbdavis** [YannBrrd/elasticsearch-entity-resolution#18]
I've been trying to get this to install under the latest version of elasticsearch (2.1.0), and below are notes on various problems and resolutions I've encountered.

If I follow the instructions on  [How to install](https://github.com/YannBrrd/elasticsearch-entity-resolution/wiki/install) page:

```bin/plugin install http://dl.bintray.com/yann-barraud/elasticsearch-entity-resolution/org/yaba/elasticsearch-entity-resolution-plugin/1.7.1.1/```

Then I get this:

```ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip```

I'm able to get it the plugin to install (although still haven't verified that it actually works correctly) if I hack the zip to include a plugin-descriptor.properties file inspired by the example [here](https://github.com/royrusso/elasticsearch-HQ/blob/master/plugin-descriptor.properties) and some trial and error:

```
description=elasticsearch-entity-resolution
version=1.7.1.1
site=false
jvm=true
name=elasticsearch-entity-resolution
java.version=1.8
elasticsearch.version=2.1.0
classname=org.yaba.entity.plugin.EntityResolutionPlugin
```

and then 

```bin/plugin install file:///path/to/elasticsearch-entity-resolution-plugin-1.7.1.1.zip```

If I try to build from source using `mvn clean package`, then I run into an issue of `Non-resolvable parent POM for org.yaba:elasticsearch-entity-resolution-plugin:2.0.0-beta2-SNAPSHOT`.  When I look [here](https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/plugin/elasticsearch-plugin/), it seems that there is no version 2.0.0-beta2-SNAPSHOT, although there is a version 2.1.0-SNAPSHOT.  Fixing this in the `pom.xml` helps things get a bit further.

There's a few more issues I ran into - it seems that the pom.xml specifies that a license check should be done, although most (all?) of the java code doesn't have this included yet.  Some of the maven tests fail, and at least for my system (Ubuntu 15.10) I get an error of `There is an incompatible JNA native library installed on this system`.  The maven command below gets around this:

`mvn clean package -Djna.nosys=true -DskipTests=true -Dlicense.skip=true`

From here I get a bit stuck.   

`bin/plugin install file:///path/to/elasticsearch-entity-resolution/target/releases/elasticsearch-entity-resolution-plugin-2.1.0-SNAPSHOT.zip`

then leads to:

```NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: java.lang.IllegalStateException: jar hell!
class: com.google.common.annotations.Beta
jar1: /usr/share/elasticsearch/lib/guava-18.0.jar
jar2: /tmp/4093884876277737848/temp_name767386312/guava-18.0.jar```

The md5 issue makes sense, but I'm not sure what to do yet about the `jar hell!`.

**Comment by YannBrrd** [comment]
Hi,

I'm late in releasing the 2.X versions. I'll do this ASAP...

Sorry for the delay.

Cheers,
Yann

Le mer. 25 nov. 2015 à 21:47, Chris Davis <notifications@github.com> a
écrit :

> I've been trying to get this to install under the latest version of
> elasticsearch (2.1.0), and below are notes on various problems and
> resolutions I've encountered.
>
> If I follow the instructions on How to install
> <https://github.com/YannBrrd/elasticsearch-entity-resolution/wiki/install>
> page:
>
> bin/plugin install
> http://dl.bintray.com/yann-barraud/elasticsearch-entity-resolution/org/yaba/elasticsearch-entity-resolution-plugin/1.7.1.1/
>
> Then I get this:
>
> ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in
> plugin zip
>
> I'm able to get it the plugin to install (although still haven't verified
> that it actually works correctly) if I hack the zip to include a
> plugin-descriptor.properties file inspired by the example here
> <https://github.com/royrusso/elasticsearch-HQ/blob/master/plugin-descriptor.properties>
> and some trial and error:
>
> description=elasticsearch-entity-resolution
> version=1.7.1.1
> site=false
> jvm=true
> name=elasticsearch-entity-resolution
> java.version=1.8
> elasticsearch.version=2.1.0
> classname=org.yaba.entity.plugin.EntityResolutionPlugin
>
> and then
>
> bin/plugin install
> file:///path/to/elasticsearch-entity-resolution-plugin-1.7.1.1.zip
>
> If I try to build from source using mvn clean package, then I run into an
> issue of Non-resolvable parent POM for
> org.yaba:elasticsearch-entity-resolution-plugin:2.0.0-beta2-SNAPSHOT.
> When I look here
> <https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/plugin/elasticsearch-plugin/>,
> it seems that there is no version 2.0.0-beta2-SNAPSHOT, although there is a
> version 2.1.0-SNAPSHOT. Fixing this in the pom.xml helps things get a bit
> further.
>
> There's a few more issues I ran into - it seems that the pom.xml specifies
> that a license check should be done, although most (all?) of the java code
> doesn't have this included yet. Some of the maven tests fail, and at least
> for my system (Ubuntu 15.10) I get an error of There is an incompatible
> JNA native library installed on this system. The maven command below gets
> around this:
>
> mvn clean package -Djna.nosys=true -DskipTests=true -Dlicense.skip=true
>
> From here I get a bit stuck.
>
> bin/plugin install
> file:///path/to/elasticsearch-entity-resolution/target/releases/elasticsearch-entity-resolution-plugin-2.1.0-SNAPSHOT.zip
>
> then leads to:
>
> NOTE: Unable to verify checksum for downloaded plugin (unable to find
> .sha1 or .md5 file to verify)
> ERROR: java.lang.IllegalStateException: jar hell!
> class: com.google.common.annotations.Beta
> jar1: /usr/share/elasticsearch/lib/guava-18.0.jar
> jar2: /tmp/4093884876277737848/temp_name767386312/guava-18.0.jar
>
> The md5 issue makes sense, but I'm not sure what to do yet about the jar
> hell!.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YannBrrd/elasticsearch-entity-resolution/issues/18>.
>
-- 
Cordialement,
Yann Barraud

**Comment by cbdavis** [comment]
Cool, I'm looking forward to it...

**Comment by YannBrrd** [comment]
Fixed. See doc & bintray
