### ISSUE TITLE
Error while installing plugin version 2.1.0

### ISSUE THREAD

**Issue by ofergold** [YannBrrd/elasticsearch-entity-resolution#20]
I’m using the official elasticsearch docker container, which is version 2.1.1. 
After running "plugin install" with a link to version 2.1.0 of the plugin I get the below output. Any help would be greatly appreciated. Thanks in advance!

plugin install http://dl.bintray.com/yann-barraud/elasticsearch-entity-resolution/org/yaba/elasticsearch-entity-resolution-plugin/2.1.0/
-> Installing from http://dl.bintray.com/yann-barraud/elasticsearch-entity-resolution/org/yaba/elasticsearch-entity-resolution-plugin/2.1.0/...
Trying http://dl.bintray.com/yann-barraud/elasticsearch-entity-resolution/org/yaba/elasticsearch-entity-resolution-plugin/2.1.0/ ...
Downloading ..DONE
Verifying http://dl.bintray.com/yann-barraud/elasticsearch-entity-resolution/org/yaba/elasticsearch-entity-resolution-plugin/2.1.0/ checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by brusic** [comment]
I suspect there is something wrong with the elasticsearch plugin script since I had the same issue. I am able to install locally using the file that was downloaded with the same script:

bin/plugin install file:./elasticsearch-entity-resolution-plugin-2.1.0.zip

**Comment by ofergold** [comment]
Thank you brusic!
That probably would have worked but I'm on es 2.1.1 so I'm getting the following:

plugin install file:elasticsearch-entity-resolution-plugin-2.1.0.zip
-> Installing from file:elasticsearch-entity-resolution-plugin-2.1.0.zip...
Trying file:elasticsearch-entity-resolution-plugin-2.1.0.zip ...
Downloading .......DONE
Verifying file:elasticsearch-entity-resolution-plugin-2.1.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Plugin [elasticsearch-entity-resolution-plugin] is incompatible with Elasticsearch [2.1.1]. Was designed for version [2.1.0]

**Comment by brusic** [comment]
The elastic team made it very difficult for plugin developers. Each plugin needs to be re-released for each  version, no matter how minor.

You can either use elasticsearch 2.1.0 or compile the plugin yourself. Change the pom.xml and descriptor for the new version, there should be no changes. If it works, submit the changes back as a PR! :)

**Comment by YannBrrd** [comment]
plugin-descriptor is generated at build time... Just pushing 2.1.1 in bintray ATM... Stay tuned
