### ISSUE TITLE
Usage to remove duplicate documents from elasticsearch

### ISSUE THREAD

**Issue by madhvi-gupta** [YannBrrd/elasticsearch-entity-resolution#24]
Hi,

I want to use elasticsearch entity resolution to remove duplicate documents or to find various relationship among the documents on the basis of some fields.Can you please share any document or details about the usage of this plugin as I didn't found any.

Thanks in advance.

**Comment by YannBrrd** [comment]
Please check [Wiki](https://github.com/YannBrrd/elasticsearch-entity-resolution/wiki/Run-Examples)
