### ISSUE TITLE
Error while installing plugin version 2.2.0

### ISSUE THREAD

**Issue by KonstantinaLazaridou** [YannBrrd/elasticsearch-entity-resolution#27]
I am trying to install the plugin (version 2.2.0 currently) and no matter the way I try it fails to be installed. I am not sure which command to use, since the recommended "plugin -i entity-resolution -url  http://goo.gl/DGQuUe" is not working. 

I get the following errors:

**bin/plugin -i entity-resolution -url  http://goo.gl/DGQuUe**
-> Installing entity-resolution...
Trying http://goo.gl/DGQuUe...
Failed: IOException[Can't get http://goo.gl/DGQuUe to /data/websci/elasticsearch/elasticsearch-1.5.0/plugins/entity-resolution.zip]; nested: FileNotFoundException[http://dl.bintray.com/yann-barraud/elasticsearch-entity-resolution-plugin#elasticsearch-identity-resolution-plugin-0.1.zip]; nested: FileNotFoundException[http://dl.bintray.com/yann-barraud/elasticsearch-entity-resolution-plugin#elasticsearch-identity-resolution-plugin-0.1.zip];
Trying https://github.com/null/entity-resolution/archive/master.zip...
Failed to install entity-resolution, reason: failed to download out of all possible locations..., use --verbose to get detailed information

I also tried installing it manually by downloading the file and executing this command 
**bin/plugin install file:plugins/elasticsearch-entity-resolution-plugin-2.2.0.0.zip**
, which again didn't work. 

This is the error:

Trying https://github.com/file:plugins/elasticsearch-entity-resolution-plugin-2.2.0.0.zip/archive/master.zip...
Failed to install file:plugins/elasticsearch-entity-resolution-plugin-2.2.0.0.zip, reason: failed to download out of all possible locations..., use --verbose to get detailed information

I also tried lots of urls and most of the times the error is either:

Error while installing plugin, reason: IllegalArgumentException: Plugin installation assumed to be site plugin, but contains source code, aborting installation.

or

Error while installing plugin, reason: IllegalArgumentException: Plugin installation assumed to be site plugin, but contains source code, aborting installation.
konstantina.lazaridou@isfet:/data/websci/elasticsearch/elasticsearch-1.5.0$ bin/plugin -u -v install larsga/elasticsearch-entity-resolution

or 

Error while installing plugin, reason: ElasticsearchIllegalArgumentException: Illegal plugin name:

**Comment by YannBrrd** [comment]
Hi,

Just download the 2.2.0 zip file and install like in documentation https://www.elastic.co/guide/en/elasticsearch/plugins/2.2/installation.html

**Comment by KonstantinaLazaridou** [comment]
I have already mentioned above that I tried to use the documentation and it doesn't work. Both for urls and files.
This command:
** bin/plugin install file:plugins/elasticsearch-entity-resolution-plugin-2.2.0.0.zip** 
doesn't work and shows the above errors.
